--sqlplus sys as sysdba
--p

CREATE USER "MERCHANT_COLES" PROFILE "DEFAULT"
IDENTIFIED BY "p" DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "MERCHANT_COLES";
GRANT "RESOURCE" to "MERCHANT_COLES";
GRANT "CONNECT" TO "MERCHANT_COLES";
GRANT "DBA" TO "MERCHANT_COLES";

--impdp system dumpfile=MERCHANT_COLES_TEST_export_20160929.dump logfile=MERCHANT_COLES_TEST_impdp.log TRANSFORM=OID:n REMAP_SCHEMA=MERCHANT_COLES_TEST:MERCHANT_COLES


--impdp system dumpfile=MERCHANT_COLES_TEST_export_20160929.dump logfile=你喜欢.log remap_schema=XXX:本地帐号  remap_tablespace=USERS:USERS
--这样就OK了，主要是remap_schema要对应
--这个路径是在安装oracle的时候顺便设定的
